# Generated by Django 5.0 on 2024-09-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0002_user_date_create"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="date_create",
        ),
    ]
