# Generated by Django 5.0 on 2024-09-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0004_user_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
