# Generated by Django 5.0 on 2024-08-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complain_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="created_by",
        ),
    ]
