# Generated by Django 5.0 on 2024-09-01 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complain_app", "0003_complaint_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification", models.CharField(max_length=200)),
                (
                    "complain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="complain_app.complaint",
                    ),
                ),
            ],
        ),
    ]
