# Generated by Django 5.0 on 2024-09-01 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complain_app", "0004_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
