# Generated by Django 5.0 on 2024-09-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complain_app", "0007_alter_feedback_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="complain_files/"),
        ),
    ]
