# Generated by Django 5.0 on 2024-10-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complain_app", "0010_alter_complaint_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="title",
        ),
    ]
